import React from 'react';
import { Layout, Menu, MenuProps } from 'antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Content, Header, Footer } from 'antd/es/layout/layout';
import { NavMenu } from './NavMenu';

export const metadata = {
  title: 'Popoco Studio',
  description: 'Generated by Next.js',
};
const items: MenuProps['items'] = [
  {
    label: '首页',
    key: 'home',
  },
  {
    label: '关于',
    key: 'about',
  },
  {
    label: '用户中心',
    key: 'member',
  },
]; 


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const menu_click: MenuProps['onClick'] = (e) => {
    console.log(e)
  }
  return (
    <html lang="en" style={{ height: '100%' }}>
      <AntdRegistry>
        <body style={{ height: '100%', margin: 0 }}>
          <div id="__next" style={{ display: 'flex', flexDirection: 'column', minHeight: '100%' }}>
            <Layout>
              <Header style={{display: 'flex',flexDirection:'column',paddingLeft: '0px',paddingRight: '0px'}}>
                {/* <Menu onClick={menu_click} items={items} mode="horizontal" /> */}
                <NavMenu />
              </Header>
              <Content style={{ flex: 1 }}>{children}</Content>
              <Footer style={{height: "12vh",textAlign: "center"}}>
                <h4>Popoco Studio</h4>
                <h4>Copyright 2024,All rights Reserved.</h4>
              </Footer>
            </Layout>
          </div>
        </body>
      </AntdRegistry>
    </html>
  );
}
